in_bucket_name  = "test-in-dev-oct2401"
out_bucket_name = "test-out-dev-oct2401"
tmp_bucket_name = "test-tmp-dev-oct2401"
export_bucket_name = "test-export-dev-oct2401"
environment = "dev"
# TF_STATE_BUCKET = "sit-terraform-state-bucket"
# TF_STATE_LOCK_TABLE = "sit-terraform-lock-table"
# AWS_REGION = "us-east-1"