# TF_STATE_BUCKET = "your-prod-tf-state-bucket"
in_bucket_name  = "test-in-prod-oct2401"
out_bucket_name = "test-out-prod-oct2401"
tmp_bucket_name = "test-tmp-prod-oct2401"
export_bucket_name = "test-export-prod-oct2401"
environment = "prod"
# bucket_name = "your-prod-bucket-name"
