name: Bootstraping v1

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Specify the environment to destroy (dev, sit, prod)'
        required: true
        default: 'dev'

jobs:
  create-resources:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required for checking out the code
    environment:
      name: ${{ inputs.environment }}  # Dynamically use the environment (dev, sit, prod)

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Dynamically set the role ARN and AWS region
      - name: Set role ARN and AWS region for environment
        run: |
          echo "ROLE_ARN=${{ secrets['AWS_' + inputs.environment + '_ROLE_ARN'] }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV  # Set AWS region as an environment variable

      # Step 3: Debug to check if AWS_REGION is set correctly
      - name: Debug AWS_REGION
        run: |
          echo "AWS_REGION=${{ secrets.AWS_REGION }}"
          echo "AWS_REGION from env=${{ env.AWS_REGION }}"

      # Step 4: Set up AWS OIDC credentials
      - name: Set up AWS OIDC credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}  # Directly pass the region from the environment variable
