name: Deploy to DEV environment

on:
  push:
    branches:
      - 'feature/*'  # Trigger on any push to a feature branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required for checking out the code

    environment:
        name: dev  # Set the environment as 'dev'
    
    env:
      AWS_ROLE_ARN: ${{ secrets.AWS_DEV_ROLE_ARN }}  # Set AWS role ARN for DEV
      AWS_REGION: ${{ secrets.AWS_REGION }}  # Set AWS region
      TF_VAR_TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}  # S3 bucket for state storage
      TF_STATE_LOCK_TABLE: ${{ secrets.TF_STATE_LOCK_TABLE_DEV }}  # Reference the DEV DynamoDB table secret

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      # Optional: Check Environment Variables for debugging
      - name: Check Environment Variables
        run: |
          echo "AWS_ROLE_ARN: ${{ secrets.AWS_DEV_ROLE_ARN }}"
          echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
          echo "TF_VAR_TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}"
          echo "TF_STATE_LOCK_TABLE: ${{ secrets.TF_STATE_LOCK_TABLE_DEV }}"

      # Configure AWS credentials with the role to assume
      - name: Configure AWS credentials
        id: aws_auth
        uses: aws-actions/configure-aws-credentials@v3 
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN }}  # Assume the provided AWS role ARN for DEV
          aws-region: ${{ secrets.AWS_REGION }}  # Set the AWS region

      # Auto-format Terraform code (optional but useful for clean code)
      - name: Terraform Format (Auto-fix)
        run: |
          set -e
          terraform fmt -recursive  # Automatically format all files in the repository

      # Terraform initialization to configure the backend
      - name: Terraform Init
        run: |
          set -e
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=terraform/dev/dev.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE_DEV }}"  # Use the DEV DynamoDB table for locking

      # Validate the Terraform configuration (good practice before applying changes)
      - name: Terraform Validate
        run: |
          set -e
          terraform validate

      # Create the execution plan to preview the changes
      - name: Terraform Plan
        id: plan
        run: |
          set -e
          terraform plan -out=tfplan -var-file=environments/dev.tfvars  # Use environment-specific variables file

      # Check if there are changes in the plan, and skip apply if none
      - name: Check for Changes in Plan
        run: |
          set -e
          if terraform show tfplan | grep -q 'No changes. Infrastructure is up-to-date.'; then
            echo "No changes to apply."
            exit 0  # Exit early if no changes
          fi

      # Apply the Terraform plan if there are changes
      - name: Terraform Apply
        run: |
          set -e
          terraform apply -auto-approve tfplan  # Apply the changes

      # Ensure we clean up the workspace after the job
      - name: Cleanup Terraform workspace
        run: |
          terraform workspace select default || terraform workspace new default
