name: Deploy to DEV environment

on:
  push:
    branches:
      - 'feature/*'  # Trigger on any push to a feature branch

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC authentication
      contents: read    # Required for checking out the code

    environment:
      name: dev  # Dynamic environment for DEV

    env:
      AWS_ROLE_ARN: ${{ secrets.AWS_DEV_ROLE_ARN }}  # Role ARN for DEV
      AWS_REGION: ${{ secrets.AWS_REGION }}  # AWS Region
      TF_VAR_TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET_DEV }}  # S3 bucket for state storage
      TF_STATE_BUCKET_KEY: "terraform/dev/terraform_backend_config.tfstate"  # Key for DEV state file

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Configure AWS credentials
        id: aws_auth
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform Backend
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET_DEV }}" \
    
