name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC.
      contents: read        
    env:
      TF_VAR_TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}  # S3 bucket for TF state

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.8
      
      - name: Check Environment Variables
        run: env
          
      - name: Configure AWS credentials
        id: aws_auth
        uses: aws-actions/configure-aws-credentials@v3 
        with:
          role-to-assume: ${{ secrets.AWS_PROD_ROLE_ARN }}  # Role for AWS production
          aws-region: ${{ secrets.AWS_REGION }}  # AWS region

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=terraform/prod.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan -var-file=environments/prod.tfvars

      - name: Check for Changes in Plan
        run: |
          if terraform show tfplan | grep -q 'No changes. Infrastructure is up-to-date.'; then
            echo "No changes to apply."
            exit 0  # Skip apply if no changes
          fi

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan  # Apply the planned changes
