name: Deploy to SIT

on:
  pull_request_review:
    types: [submitted]  # Focus on review events
    branches:
      - main

jobs:
  deploy:
    if: github.event.review.state == 'approved'  # Proceed only if approved
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read      

    environment:
        name: sit 
        
    env:
      AWS_ROLE_ARN: ${{ secrets.AWS_SIT_ROLE_ARN }}  # Use the AWS role from secrets
      AWS_REGION: ${{ secrets.AWS_REGION }}  # Use the AWS region from secrets
      TF_VAR_TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}  # S3 bucket for Terraform state

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 for Node.js 16 compatibility

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Updated to v2 for Node.js 16 compatibility
        with:
          terraform_version: 1.9.8  # Ensure this is the latest stable version

      - name: Configure AWS credentials
        id: aws_auth
        uses: aws-actions/configure-aws-credentials@v3 
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}  # Use the environment variable
          aws-region: ${{ env.AWS_REGION }}  # Use the environment variable

      - name: Terraform Init
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=terraform/sit.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"  # Use the environment variable

      - name: Terraform Plan
        id: plan
        run: |
          set -e
          terraform plan -out=tfplan -var-file=environments/sit.tfvars

      - name: Check for Changes in Plan
        run: |
          set -e
          if terraform show tfplan | grep -q 'No changes. Infrastructure is up-to-date.'; then
            echo "No changes to apply."
            exit 0  # Skip apply if no changes
          fi

      - name: Terraform Apply
        run: |
          set -e
          terraform apply -auto-approve tfplan
