name: Terraform Apply

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "aws_region=${{ secrets.AWS_REGION }}" -var "bucket_name=testbucketoooo007"

      - name: Terraform Apply
        run: terraform apply -var "aws_region=${{ secrets.AWS_REGION }}" -var "bucket_name=testbucketoooo007" -auto-approve
