name: Destroy Terraform Resources

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Specify the environment to destroy (e.g., sit, prod, dev)'
        required: true
        default: 'sit'

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}  # Dynamically use the input environment

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Access to repository contents

    env:
      # Use explicit environment checks instead of format()
      AWS_ROLE_ARN: ${{ secrets.AWS_SIT_ROLE_ARN }}  # Default to SIT
      AWS_REGION: ${{ secrets.AWS_REGION }}  # AWS region
      TF_VAR_TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}  # Terraform state bucket

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the code

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8  # Set the Terraform version

      - name: Configure AWS credentials
        id: aws_auth
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_SIT_ROLE_ARN }}  # Default to SIT
          aws-region: ${{ secrets.AWS_REGION }}  # Use AWS region
        env:
          AWS_ROLE_ARN: ${{ secrets.AWS_SIT_ROLE_ARN }}  # Default to SIT
          AWS_REGION: ${{ secrets.AWS_REGION }}  # Use the AWS region
          TF_VAR_TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}  # Terraform state bucket

      # Dynamically select the correct role and terraform files based on input environment
      - name: Set environment-specific values
        run: |
          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "Setting PROD environment variables"
            echo "AWS_ROLE_ARN=${{ secrets.AWS_PROD_ROLE_ARN }}" >> $GITHUB_ENV
            echo "TF_VAR_TF_STATE_BUCKET=${{ secrets.PROD_TF_STATE_BUCKET }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "sit" ]; then
            echo "Setting SIT environment variables"
            echo "AWS_ROLE_ARN=${{ secrets.AWS_SIT_ROLE_ARN }}" >> $GITHUB_ENV
            echo "TF_VAR_TF_STATE_BUCKET=${{ secrets.TF_STATE_BUCKET }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "dev" ]; then
            echo "Setting DEV environment variables"
            echo "AWS_ROLE_ARN=${{ secrets.AWS_DEV_ROLE_ARN }}" >> $GITHUB_ENV
            echo "TF_VAR_TF_STATE_BUCKET=${{ secrets.DEV_TF_STATE_BUCKET }}" >> $GITHUB_ENV
          fi

      - name: Terraform Init (Destroy)
        run: |
          set -e  # Exit on error
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=terraform/${{ github.event.inputs.environment }}.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"  # Use AWS region dynamically

      - name: Terraform Plan (Destruction)
        run: |
          set -e
          terraform plan -destroy -out=tfplan -var-file=environments/${{ github.event.inputs.environment }}.tfvars  # Plan for the destruction
          terraform show -no-color tfplan  # Show the plan for review

      - name: Manual Approval for Destruction (Critical Environments Only)
        if: ${{ github.event.inputs.environment == 'prod' }}  # Manual approval required for production
        run: |
          echo "Please manually approve the destruction for the prod environment."
          exit 1  # Exit to wait for manual approval (you can handle manual approval in the GitHub environment settings)

      - name: Terraform Destroy
        run: |
          set -e
          terraform apply -auto-approve tfplan  # Apply the destruction plan (only after approval if prod)
        if: ${{ github.event.inputs.environment != 'prod' }}  # Skip for prod if manual approval is required
