name: Terraform Apply

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true  # Enable debugging for all steps
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      
      - name: Check Environment Variables
        run: env
          
      - name: Configure AWS credentials
        id: aws_auth
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./terraform-testing
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform-testing
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform-testing
        run: terraform apply -auto-approve
