# name: Terraform Apply
 
# on:
#   push:
#     branches:
#       - dev  # Trigger on changes to the 'main' branch
 
# jobs:
#   terraform:
#     name: Terraform Apply
#     runs-on: ubuntu-latest
 
#     permissions:
#       id-token: write  # Required for OIDC
#       contents: read
 
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
 
#       - name: Configure AWS credentials using OIDC
#         uses: aws-actions/configure-aws-credentials@v3
#         with:
#           role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN }} #  IAM Role ARN
#           aws-region: ${{ secrets.AWS_REGION }}  # AWS region
 
#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.9.8  
 
#       - name: Terraform Init
#         run: terraform init
 
#       - name: Terraform Plan
#         run: terraform plan
 
#       - name: Terraform Apply
#         run: terraform apply -auto-approve
 
name: Terraform Apply

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN }} # Use the secret for the IAM Role ARN
          aws-region: ${{ secrets.AWS_REGION }}  # Use the secret for the AWS region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "aws_region=${{ secrets.AWS_REGION }}" -var "bucket_name=my-unique-bucket-name" -var "environment=dev"

      - name: Terraform Apply
        run: terraform apply -var "aws_region=${{ secrets.AWS_REGION }}" -var "bucket_name=my-unique-bucket-name" -var "environment=dev" -auto-approve
