name: Terraform Destroy Specific

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'dev'

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}  # Dynamically use environment input
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_SIT_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Plan (Destruction)
        run: |
          terraform init
          terraform plan -destroy -out=tfplan -var-file=environments/${{ github.event.inputs.environment }}.tfvars
          terraform show -no-color tfplan

      - name: Manual Approval for Destruction
        if: github.event.inputs.environment == 'prod'  # For production, manual approval is required
        run: |
          echo "Please manually approve the destruction for prod."

      - name: Terraform Destroy
        if: github.event.inputs.environment != 'prod'  # Skip in prod if manual approval is required
        run: |
          terraform apply -auto-approve tfplan
